/*
 * This source file was generated by the Gradle 'init' task
 */
package org.zgsolucoes;

import org.zgsolucoes.view.MenuView;

public class App {
    public static void main(String[] args) {
        MenuView menuView = new MenuView();
        menuView.exibeMenu();
    }
}
